namespace RssView
{
    [bindable]
    [default_interface]
    runtimeclass Item : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        Item(String title, String content);
        String Title{ get; };
        String Content{ get; };
        
    }
}
