import "ItemViewModel.idl";

namespace RssView
{
    [default_interface]
    runtimeclass MainPage : Windows.UI.Xaml.Controls.Page
    {
        MainPage();
        ItemViewModel RssItemsViewModel{ get; };
    }
}
